import { StyleSheet } from "react-native";
const Add_Request_styles = StyleSheet.create({
  container: {
    backgroundColor: "#ffe713",
    height: "100%",
  },
  btn_txt: {
    color: "white",
    fontSize: 17,
    fontFamily: "Poppins_500Medium",
  },
  btn_next: {
    marginTop: "7%",
    height: 50,
    borderColor: "black",
    borderRadius: 4,
    backgroundColor: "#53ab1b",
    width: 286,
    alignContent: "center",
    alignItems: "center",
    padding: 10,
    marginBottom: "80%",
    alignSelf: "center",
  },
  header: {
    alignItems: "center",
    alignContent: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  headerTitle: {
    paddingTop: "10%",
    fontSize: 18,
    fontFamily: "Poppins_500Medium",
    paddingBottom: "2.2%",
  },
  dataContainer: {
    marginTop: "5%",
  },
  innerButtonView: {
    flexDirection: "row",
    borderWidth: 0.8,
    borderColor: "#E4E9F3",
    backgroundColor: "#E4E9F3",
    borderRadius: 5,
    marginTop: "2%",
    height: 65,
    width: "95%",
    alignItems: "center",
  },
  containerText: {
    fontFamily: "Poppins_500Medium",
    fontSize: 16,
    marginLeft: "7%",
  },
  backStyle: {
    paddingTop: "8%",
    paddingLeft: "6%",
  },
  innerContainer: {
    flex: 10,
    backgroundColor: "white",
    borderTopRightRadius: 50,
    borderTopLeftRadius: 50,
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 11,
    },
    shadowOpacity: 0.67,
    shadowRadius: 15.19,
    elevation: 60,
    height: "200%",
  },
  innerText: {
    fontSize: 12,
    fontFamily: "Poppins_600SemiBold",
    marginLeft: "7%",
  },
  loadmore: {
    margin: "9%",
    flexDirection: "row",
    alignSelf: "center",
    height: 90,
  },
  input: {
    borderColor: "#E4E9F3",
    height: 45,
    margin: 20,
    borderWidth: 1.0,
    padding: 10,
    borderRadius: 3,
  },
  label: {
    paddingLeft: "5%",
    paddingTop: "5%",
    fontFamily: "Poppins_600SemiBold",
    fontSize: 12,
  },
  containerText: {
    fontFamily: "Poppins_500Medium",
    fontSize: 16,
    marginLeft: "7%",
    marginTop: "2%",
  },
  Notes: {
    borderWidth: 0.8,
    borderColor: "#E4E9F3",
    borderRadius: 6,
    paddingTop: "2%",
    paddingLeft: "2%",

    backgroundColor: "white",
    marginTop: "2%",
    marginLeft: "7%",
    marginRight: "7%",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",

    height: 43,
  },
});
export default Add_Request_styles;
