import { StyleSheet } from "react-native";
import GlobalColors from "../../../Utils/GlobalColors";
const Pickup_History_styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFE713",
  },
  Calnder_View: {
    width: "100%",
    height: 50,
    flexDirection: "row",
    padding: 5,
    borderWidth: 1,
    borderRadius: 6,
    borderColor: GlobalColors.Bordercolor,
  },
  Dropdown_Arrow: {
    alignSelf: "center",
    position: "absolute",
    right: 20,

    width: 9.9,
    height: 6.36,
  },
  calnderImg: {
    flexDirection: "row",
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
  },
  calander_date_txt: {
    fontSize: 14,
    width: "90%",
    color: GlobalColors.TXTGray,
    fontFamily: "Poppins_600SemiBold",
  },
  SortView: {
    flexDirection: "row",
    padding: 12,
    alignContent: "center",
    alignItems: "center",
    justifyContent: "space-between",

    borderWidth: 1.9,
    borderRadius: 6,
    borderColor: "#E4E9F3",
    height: 43,
    width: "100%",
  },
  filterStyle: {
    fontSize: 12,
    fontFamily: "Poppins_600SemiBold",
    paddingBottom: 10,
    paddingLeft: 5,
  },
  calanderpicker_view: {
    marginTop: "46%",
    width: "91%",
    height: 244,
    alignSelf: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderWidth: 0.3,
    borderColor: "#E4E9F3",
    borderRadius: 5,
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 11,
    },
    shadowOpacity: 0.57,
    shadowRadius: 15.19,

    elevation: 23,
  },
  innerViewStyle: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: "6%",
    width: "100%",
  },
  innerText: {
    fontSize: 12,
    paddingLeft: "5%",
    paddingRight: "5%",
    fontFamily: "Poppins_600SemiBold",
  },
  filterView: {
    marginLeft: "6%",
    marginRight: "6%",
    marginTop: "2%",
  },
  buttonView1: (bgcolor) => ({
    backgroundColor: bgcolor,
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    width: 105,
    height: 32,

    borderWidth: 0.15,
    borderColor: "#707070",
    borderRadius: 2,
  }),
  buttonView2: (bgcolor2) => ({
    backgroundColor: bgcolor2,
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    width: 105,
    height: 32,
    borderWidth: 0.15,
    borderColor: "#707070",
    borderRadius: 2,
  }),
  buttonView3: (bgcolor3) => ({
    backgroundColor: bgcolor3,
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    width: 105,
    height: 32,
    borderWidth: 0.15,
    borderColor: "#707070",
    borderRadius: 2,
  }),
  innerContainer: {
    flex: 10,
    borderTopRightRadius: 50,
    borderTopLeftRadius: 50,
    backgroundColor: "white",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.9,
    shadowRadius: 8,
    elevation: 30,
  },
  header: {
    alignItems: "center",
    alignContent: "center",
    flexDirection: "row",
  },
  scrollview_style: {
    marginLeft: "4%",
    marginRight: "5%",
    marginTop: "12%",
    backgroundColor: "white",
  },
  headerTitle: {
    paddingLeft: "25%",
    paddingTop: "10%",
    fontFamily: "Poppins_500Medium",
    fontSize: 18,
    fontWeight: "700",
    // fontFamily:'Inter_900Black',
    paddingBottom: "2.2%",
  },
  backStyle: {
    paddingTop: "8%",
    paddingLeft: "6%",
  },
  dataContainer: {
    margin: 35,
  },
  filterStyle: {
    fontSize: 12,
    fontWeight: "bold",
    paddingBottom: 10,
    paddingLeft: 5,
    fontFamily: "Poppins_600SemiBold",
  },

  calenderView: {
    flexDirection: "row",
    padding: 10,
    borderWidth: 1.9,
    borderColor: "#E4E9F3",
  },

  home_txt: {
    fontSize: 20,
    paddingLeft: "30%",
    fontWeight: "bold",
    alignSelf: "center",
  },
  loadmore: {
    flexDirection: "row",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    height: 90,
  },
});
export default Pickup_History_styles;
