import { StyleSheet } from "react-native";

const Pickup_History_Detail_Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFE713",
  },
  itemsimgview: {
    paddingTop: "2%",
    flexDirection: "row",
  },
  statusbutton: {
    marginTop: "8%",
    marginBottom: "6%",
    width: "100%",
    height: 54,
    marginRight: "5%",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E4E9F3",
    fontSize: 12,
    fontFamily: "Poppins_500Medium",
  },
  statustext: {
    color: "#51AB1D",
    fontSize: 18,
    fontFamily: "Poppins_600SemiBold",
  },

  innerContainer: {
    flex: 10,
    paddingTop: "10%",
    paddingLeft: "5%",
    paddingRight: "5%",
    backgroundColor: "transparent",
    borderTopRightRadius: 50,
    borderTopLeftRadius: 50,
    backgroundColor: "white",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.9,
    shadowRadius: 8,
    elevation: 30,
  },
  header: {
    alignItems: "center",
    alignContent: "center",
    flexDirection: "row",
  },
  headerTitle: {
    paddingLeft: "20%",
    paddingTop: "10%",
    fontFamily: "Poppins_500Medium",
    fontSize: 18,
    fontWeight: "700",
    // fontFamily:'Inter_900Black',
    paddingBottom: "2.2%",
  },
  backStyle: {
    paddingTop: "8%",
    paddingLeft: "6%",
  },
  dataContainer: {
    margin: 35,
  },
  filterStyle: {
    fontSize: 12,
    fontWeight: "bold",
    paddingBottom: 10,
    paddingLeft: 5,
    fontFamily: "Poppins_600SemiBold",
  },

  calenderView: {
    flexDirection: "row",
    padding: 5,
    borderWidth: 1.9,
    borderRadius: 6,
    borderColor: "#51AB1D",
    paddingLeft: "8%",
  },
  home_txt: {
    fontSize: 20,
    paddingLeft: "30%",
    fontWeight: "bold",
    alignSelf: "center",
  },
  Heading1: {
    fontSize: 18,
    fontFamily: "Poppins_500Medium",
  },
  idtxt: {
    fontSize: 14,
    color: "#7D828D",
    fontFamily: "Poppins_500Medium",
  },
  itemquantity: {
    fontSize: 10,
    paddingTop: "1%",
    color: "black",
    fontFamily: "Poppins_600SemiBold",
  },
  headingaddress: {
    fontSize: 14,
    paddingTop: "4%",
    color: "black",
    fontFamily: "Poppins_600SemiBold",
  },
  detailaddress: {
    fontSize: 14,
    paddingTop: "4%",
    color: "#7D828D",
    fontFamily: "Poppins_500Medium",
  },
  headingtime: {
    fontSize: 16,
    paddingTop: "2%",
    color: "black",
    fontFamily: "Poppins_500Medium",
  },
  time: {
    fontSize: 12,
    paddingTop: "4%",
    paddingRight: "2%",
    color: "#6E6E6E",
    fontFamily: "Poppins_500Medium",
  },
  notes: {
    height: 60,
    fontSize: 12,
    paddingRight: "4%",
    paddingTop: "4%",
    color: "black",
    fontFamily: "Poppins_400Regular",
  },
  warehousemanager: {
    fontSize: 16,
    paddingTop: "4%",
    color: "#51AB1D",
    fontFamily: "Poppins_600SemiBold",
  },
  text_input: {
    marginTop: 5,
    borderRadius: 5,
    padding: 12,
    width: "100%",
    height: 45,
    color: "gray",
    borderWidth: 1,
    borderColor: "#E4E9F3",
    fontSize: 12,
    fontFamily: "Poppins_500Medium",
  },
});
export default Pickup_History_Detail_Styles;
