export default {
  CLEARFILTER: "clear filter",
  RECYCLE: "Recycle",
  HOW_TO_RECYCLE: "How To Recycle",
  ECOREWARD: "Eco Reward",
  HISTORY: "History",
  RECYCLEORDER: "Recycle Order",
  SETTING: "Settings",
  HOME: "Home",
  NOTIFICATIONS: "Notifications",
  PROFILE: "Profile",
  CONTACTUS: "Contact us",
  LANGUAGES: "Languages",
  SPANISH: "Español",
  ENGLISH: "English",
  SelectDate: "Select Date",
  SECURITYSETTING: "Security Setting",
  CHANGEPASSWORD: "Change Password",
  DELETEACCOUNT: "Delete Account",
  PRIVACYPOLICY: "Privacy Policy",
  TERMCONDITONS: "Terms Conditions",
  LOGOOUT: "Logout",
  ADDREQUEST: "Add Request",
  CHOOSERECYCLEITEM: "Choose Recycle Items",
  NEXT: "Next",
  MARKSCHEDULE: "Mark Schedule",
  SCHEDULE: "Schedule",
  ONCEONLY: "Once Only",
  MULTIPLEDATES: "Multiple Dates",
  MONTHLY: "Monthly",
  ONCEONLYSCHEDULE: "Once Only Schedule",
  ONCEONLYDESC:
    "You can Select one schedule on per day either morning or evening.",
  DAY: "Day",
  SELECTSHIFT: "Select Shift",
  SELECTSHIFTSLOT: " Select Shift Slot",
  MORNING: "Morning",
  EVENING: "Evening",
  SELECTDATESHIFT: "Select Date & Shift",
  SELECTSTARTENDTIME: "Select Start and End Time",
  PICKUPADDRESSLOCATION: "Pickup Address & Location",
  UPLOADIMG: "Upload Image",
  PRIVACYPOLICY: "Privacy Policy",
  ADMINNOTES: "Admin Notes",

  CustomerNOTES: "Customer Notes",
  THISISDUMMYTXT: "This is the Dummy Text",
  PICKUPREQLOCATION: "Pickup Request Location",
  HI: "Hi",
  WELCOMEBACK: "Welcome Back,",
  SAVE: "Save",
  ORDERCONFIRAMTION: "Order Confirmation",
  CONFIRMORDER: "Confirm Order",
  SELECTEDITEMS: "Selected Items",
  PICKUPTIME: "Pickup Time",
  DATE: "Date",
  CONFIRMORDERMODALDESC: "Your disposal request generated & assigned to you.",
  THANKYOU: "Thankyou!",
  MULTIPLEDATESSCHEDULE: "Multiple Dates Schedule",
  MULTIPLEDESC:
    "You can Select schedule for two days either morning or evening.",
  PLEASESELECTDATETIME: "Please select Date & Time",
  SELECTMORNINGSTARTENDTIME: "Select Morning Start and End Time",
  MONTHLYSCHEDULE: "Monthly Schedule",
  MONTHLYDESC:
    "You can Select upto 31 dates schedule for month either morning or evening.",
  SETDATE: "Set Date",
  PLEASESELECTSTARTEND: "Please Select Start and End Time",
  RECYCLEYOURMULTIPLE: "Recycle your multiple",
  PRODUCTSWITH: "Products with.",
  ECOREWARD: "ECO Reward",
  EARNEDPOINTS: "Earned Points",
  BALANCE: "Balance",
  CLAIMREWARD: "Claim  Reward",
  CLAIMTHEREWARD: "Claim the Reward",
  ENTERCALIMREWARD: "Enter £ to Claim Reward",
  DONATE: "Donate",
  DONATEREWARD: "Enter £ to Donate",
  REDEEM: "Redeem",
  CLAIMMODAL:
    "The minimum redeem amount is 10 €, or more with multiplies of 5€ only.",
  DONATEMODAL:
    "Donate to help the non-profit organizations that cares about the environment.",
  REDEEMPOPUPDESC:
    "Please check all entered information is correct before redeeming this amount.",
  GOBACK: "Go Back",
  CONTINUE: "Continue",
  SUCCESSREDEEMMODALDESC:
    " Your request for redeeming these points is forward successfully.",
  ENOUGHBALANCE: "Not Enough Balance",
  RECEIVEASMALL: "Receive a small",
  THANKYOUFOREFFOR: "thank you for your efforts!",
  REDEEMPOINTS: "Redeem Points",
  DONATE: "Donate",
  RECYCLED: "Recycled",
  FILTER: "Filter",
  SELECTADATE: "Select a date",
  TOTALEARNEDPOINTS: "Total Earned Points",
  SELECTDATE: "Select Date",
  EDIT: "Edit",
  DELETE: "Delete",
  NONOTIFICATIONYET: "No Notifications Yet",
  LOADMORE: "Load More",
  EMAIL: "Email",
  MOBILENO: "Mobile Number",
  PHONENO: "Phone Number",
  BUSINESSNAME: "Business Name",
  BUSINESSDEATILS: "Business Deatils",
  LICENSECODE: "License Code (CIF, DNI, NIF)",
  POSTOFFICECODE: "Post Office Code",
  ADDRESSANDLCOATION: "Address & Location",
  BUSINESSCATEGORY: "Business Category",
  STAFFINCHARGE: "Staff Incharge",
  BANKNAME: "Bank Name",
  ACCOUNTTYPE: "Account Type",
  ACCOUNTINFORMATION: "Account Information",
  ACCOUNTHOLDERNAME: "Account Holder Name",
  EDITPROFILE: "Edit Profile",
  FIRSTNAME: "FirstName",
  LASTNAME: "LastName",
  UPDATEPROFILE: "Update Profile",
  UPDATELICENSEIMG: "Update License Image",
  OTHERSTAFF: "Other Staff InCharge",
  IBAN: "IBAN",
  PLEASESELECTLOCATIONFIRST: "Please select Location First",
  CONTACTUS: "Contact Us",
  FEELFREE: "Feel free to contact Us for your",
  CONVENIENCE: "Convenience",
  CHANGEPASSWORD: "Change Password?",
  InvalidMobilenumber: "Invalid Mobile number",
  ENTERNEWPASSWORDTORESET: "Enter new password to reset.",
  NEWPASSWORD: "New Password",
  CONFIRMNEWPASSWORD: "Confirm New Password",
  CONFIRMPASSWORD: "Confirm Password",
  SUBMIT: "Submit",
  DELETEACCOUNTDES:
    "If you dont have any recycle request, you can delete account.",
  REASONTODELETE: "(Reason to delete account)",
  DELETEMYACCOUNT: "Delete My Account",
  TERMSCONDITION: "Terms & Conditions",
  HELLO: "Hello",
  ENTERYOUREMAIL: "Enter your Email",
  FORGOTPASSWORD: "Forgot Password?",
  LOGIN: "Login",
  DONTHAVEANACCOUNT: "Do not have an account?",
  REGISTER: "Register",
  PASSWORD: "Password",
  BUSINESS: "Business",
  INDIVIDUAL: "Individual",
  OPTIONNOTAVAIL: "This option is not available yet",
  ENTERFIRSTNAME: "Enter First Name",
  ENTERLASTNAME: "Enter Last Name",
  BUSINESSHOURS: "Business Hours",
  ADDSHIFT: "Add Shift",
  ADDANOTHERSHIFT: "Add Another Shift",
  UPLOADLICENSEIMAGE: "Upload License Image",
  IDOACCEPT: "I do accept the ",
  CHANGEYOURPASSWORD: "Change Your Password",
  CHANGPASSMODALDES:
    "Shorex needs to verify your identity to reset your password,OTP code sent to you through Email/Phone. Please enter your email/phone to reset password.",
  SENDCODE: "Send Code",
  EnterOTPCODE: "Enter OTP CODE",
  OTPMODALDESC:
    "Shorex needs to verify your identity to reset your password,OTP code sent to you through SMS please enter OTP code below and reset password.",
  RESENDOTP: "Resend OTP",
  ENTERNEWPASSWORD: "Enter New Password?",
  SKIP: "Skip",
  AREYOUSRURELANG: "¿Prefieres cambiar el idioma presente?.",

  AREYOURSUREACNTDEL: "Are you sure want to delete your account permanently?",
  SUREDELRECYCLE: "Are you sure you want to delete this recycle order?",
  PICKUPREQUEST: "Pickup Requests",
  PICKUPHISTORY: "Pickup History",
  VEHICLELOAD: "Vehicle Load",
  PICKUPSREQUEST: "Pickup Request",
  ROUTETOSTART: "Route To Start",
  ONGOINGROUTE: "Ongoing Route",
  SORTBY: "Sort By",
  ROUTE1: "Route 1",
  ROUTE2: "Route 2",
  ROUTE3: "Route 3",
  NOREQUESTASSIGNED: "No request assigned on this route",
  NOREQFOUND: "No request found",
  NOCOMPELTEDREQONROUT: " No completed requests on route",
  STARTROUTE: "Start Route ",
  ADDREQUEST: "Add Request",
  CUSTOMER: "Customer",
  TRANSFERTHEREQ: "Transfer the request",
  SEND: "Send",
  ROUTESTART: "Route start",
  RECEIVEITEMS: "Receive items",
  FALSEREQUEST: "False Request",
  RECEIVEITEMS: "Received Items",
  RECEIVEDQUANTITY: "Received Quantity",
  STEEL: "steel",
  UNITS: "Units",
  DRIVERSCOMMENT: "Drivers Comments",
  UPLOADIMG: "Upload image",
  DeliveredBy: "Delivered By: ( Customer Staff Name )",
  WAREHOUSEMANAGER: "Warehouse Managers",
  MANAGERNAME: "Manager Name",
  PRODUCTITEMS: "Product items",
  WAREHOUSEADRESSLOCATION: "Warehouse Address & Location",
  WAREHOUSEHOUSELCOAITON: "Warehouse Location",
  DELIVERITEMS: "Deliver Items",
  QUANTITY: "Quantity",
  COMPLETED: "Completed",
  PICKUPHISTORYDETAIL: "Pickup History Detail",
  PICKUPHISTORY: "Pickup History",
  TOTALCUSTOMER: "Total Customer",
  DRIVINGLICENSE: "Driver ID",
  VEHICLENUMBER: "Vehicle Number",
  JOININGDATE: "Joining Date",
  YES: "sí",

  PLEASEENTERCUSID: "Please Enter Customer id",
  Passwordsuccessfulyupdated: "Password successfuly updated",
  KG: "KG",
  Unit: "Unit",
  NOPRODUCT: "No products found",
  Requestmarkedasfalserequest: "request marked as false",
  drivercomments: "driver comments",
  ClienteID: "ID del cliente",
  requestmarkedasongoing: "request marked as ongoing",
  Confirmationalert: "Confirmation alert!",
  COMPLETEONGOING: "Complete Ongoing Rotue First",
  NOTES: "Notes",
  YOURREQUEST:
    'Your "Transfer The Request" has been submitted to theadministrator department with your valid reason fortransfer this task.',
  WTQTTEXT: "Quantity must be greater than 0",
  SELECTITEM:
    "Recycle request should have atleast one item with valid quantity ",
  SELECT: "select",
  PASSWORDCONTAIN11: "Password Contain Atleast 11 Char",
};
