export default {
  CLEARFILTER: "filtro claro",

  RECYCLE: "Reciclar",
  HOW_TO_RECYCLE: "Cómo reciclar",
  ECOREWARD: "Recompensa ecológica",
  HISTORY: "Historia",
  RECYCLEORDER: "Orden de reciclaje",
  SETTING: "   Ajustes   ",
  HOME: "Casa",
  NOTIFICATIONS: "Notificaciones",
  PROFILE: "Perfil",
  CONTACTUS: "Contacta con nosotras",
  LANGUAGES: "Idiomas",
  SPANISH: "Español",
  ENGLISH: "English",
  SECURITYSETTING: "Configuración de seguridad",
  CHANGEPASSWORD: "Cambiar la contraseña",
  DELETEACCOUNT: "Borrar cuenta",
  PRIVACYPOLICIY: "Política de privacidad",
  TERMCONDITONS: "Términos y condiciones",
  LOGOOUT: "Cerrar sesión",
  ADDREQUEST: "Añadir solicitud",
  CHOOSERECYCLEITEM: "Elija elementos de reciclaje",

  NEXT: "Siguiente",
  MARKSCHEDULE: "Marcar horario",
  SCHEDULE: "Calendario",
  ONCEONLY: "Por una sola vez",
  MULTIPLEDATES: "Fechas Múltiples",
  MONTHLY: "Mensual",
  ONCEONLYSCHEDULE: "Horario de una sola vez",
  ONCEONLYDESC:
    "Puede seleccionar un horario por día, ya sea por la mañana o por la noche.",
  DAY: "Día",
  SELECTSHIFT: "Seleccione Turno",
  SELECTSHIFTSLOT: "Seleccionar turno de turno",
  MORNING: "Mañana",
  EVENING: "Tardecita",
  SELECTDATESHIFT: "Seleccionar fecha y turno",
  SELECTSTARTENDTIME: "Seleccione la hora de inicio y finalización",
  PICKUPADDRESSLOCATION: "Dirección y ubicación de recogida",
  UPLOADIMG: "Cargar imagen",
  CustomerNOTES: "Cliente notas",
  ADMINNOTES: "administración notas",
  NOPRODUCT: "No se encontraron productos",
  THISISDUMMYTXT: "Este es el texto ficticio",
  PICKUPREQLOCATION: "Lugar de recogida",
  HI: "Hola ",
  WELCOMEBACK: "Bienvenido de nuevo,",
  SAVE: "Guardar",
  ORDERCONFIRAMTION: "Confirmación del pedido",
  SELECTEDITEMS: "Artículos seleccionados",
  PICKUPTIME: "Hora de recogida",
  DATE: "Fecha",
  CONFIRMORDER: "Confirmar pedido",
  CONFIRMORDERMODALDESC:
    "Su solicitud de eliminación se generó y asignado a usted.",
  THANKYOU: "¡Gracias!",
  MULTIPLEDATESSCHEDULE: "Calendario de fechas múltiples",
  MULTIPLEDESC:
    "Puede seleccionar el horario para dos días, ya sea por la mañana o por la noche.",
  PLEASESELECTDATETIME: "Seleccione Fecha y hora",
  SELECTMORNINGSTARTENDTIME:
    "Seleccione la hora de inicio y finalización de la mañana",
  MONTHLYSCHEDULE: "Horario Mensual",
  MONTHLYDESC:
    "Puede seleccionar hasta 31 fechas programadas para el mes, ya sea por la mañana o por la noche.",
  SETDATE: "Define la fecha",
  PLEASESELECTSTARTEND: "Seleccione la hora de inicio y finalización",
  RECYCLEYOURMULTIPLE: "Recicla tu múltiplo",
  PRODUCTSWITH: "Productos con.",
  ECOREWARD: "Recompensa ecológica",
  EARNEDPOINTS: "Puntos Ganados",
  BALANCE: "Balance",
  CLAIMREWARD: "Reclama recompensa",
  CLAIMTHEREWARD: "Reclama la recompensa",
  ENTERCALIMREWARD: "Ingrese £ para reclamar la recompensa",
  DONATE: "Donar",
  DONATEREWARD: "Ingrese £ para donar",
  REDEEM: "Redimir",
  CLAIMMODAL:
    "El monto mínimo de canje es de 10 €, o más con múltiplos de 5 € únicamente.",
  DONATEMODAL:
    "Done para ayudar a las organizaciones sin fines de lucro que se preocupan por el medio ambiente.",
  REDEEMPOPUPDESC:
    "Verifique que toda la información   ingresada sea correcta antes de canjear esta cantidad.",
  GOBACK: "Regresa",
  CONTINUE: "Continuar",
  SUCCESSREDEEMMODALDESC:
    " Su solicitud para canjear estos puntos se ha enviado con éxito.",
  ENOUGHBALANCE: "No hay suficiente equilibrio",
  RECEIVEASMALL: "Recibe un pequeño",
  THANKYOUFOREFFOR: "¡Gracias por tus esfuerzos!",
  REDEEMPOINTS: "Canjear puntos",
  RECYCLED: "Reciclado",
  FILTER: "Filtrar",
  SELECTADATE: "Seleccione fecha",
  TOTALEARNEDPOINTS: "Total de puntos ganados",
  SELECTDATE: "Seleccione fecha",
  EDIT: "Editar",
  DELETE: "Borrar",
  NONOTIFICATIONYET: "No hay notificaciones todavía",
  LOADMORE: "Carga más",
  EMAIL: "Correo electrónico",
  MOBILENO: "móvil",
  PHONENO: "Número de teléfono",
  BUSINESSNAME: "Nombre del Negocio",
  BUSINESSDEATILS: "Detalles comerciales",
  LICENSECODE: "Código de Licencia (CIF, DNI, NIF)",
  POSTOFFICECODE: "Código de la oficina de correos",
  ADDRESSANDLCOATION: "Dirección y ubicación",
  BUSINESSCATEGORY: "categoría de negocios",
  STAFFINCHARGE: "Personal a cargo",
  BANKNAME: "Nombre del banco",
  ACCOUNTTYPE: "Tipo de cuenta",
  ACCOUNTINFORMATION: "Información de la cuenta",
  ACCOUNTHOLDERNAME: "nombre del titular de la cuenta",
  EDITPROFILE: "Editar perfil",
  FIRSTNAME: "Primer nombre",
  LASTNAME: "Apellido",
  UPDATEPROFILE: "Actualización del perfil",
  UPDATELICENSEIMG: "Actualizar imagen de licencia",
  OTHERSTAFF: "Otro personal a cargo",
  FEELFREE: "No dude en contactarnos para su",
  IBAN: "IBAN",
  CONVENIENCE: "Conveniencia",
  CONTACTUS: "Contacta con nosotros",
  CHANGEPASSWORD: "¿Cambiar la contraseña?",
  CONFIRMPASSWORD: "Confirmar contraseña",
  InvalidMobilenumber: "Número de teléfono inválido",

  ENTERNEWPASSWORDTORESET: "Introduzca una nueva contraseña para restablecer.",
  NEWPASSWORD: "Nueva contraseña",
  CONFIRMNEWPASSWORD: "Confirmar nueva contraseña",
  SUBMIT: "Confirmar",
  DELETEACCOUNTDES:
    "Si no tiene ninguna solicitud de reciclaje, puede eliminar la cuenta.",
  REASONTODELETE: "(Razón para eliminar la cuenta)",
  DELETEMYACCOUNT: "Borrar mi cuenta",
  PRIVACYPOLICY: "Política de privacidad",
  TERMSCONDITION: "Términos y condiciones",
  HELLO: "Hola",
  ENTERYOUREMAIL: "Introduce tu correo electrónico",
  FORGOTPASSWORD: "¿Has olvidado tu contraseña?",
  LOGIN: "Acceder",
  DONTHAVEANACCOUNT: "¿No tiene una cuenta?",
  REGISTER: "Registro",
  PASSWORD: "Clave",
  BUSINESS: "Negocio",
  INDIVIDUAL: "Individual",
  OPTIONNOTAVAIL: "Esta opción aún no está disponible",
  ENTERFIRSTNAME: "Ingrese el nombre",
  ENTERLASTNAME: "Introduzca el apellido",
  BUSINESSHOURS: "Horas de trabajo",
  ADDSHIFT: "Agregar Turno",
  ADDANOTHERSHIFT: "Agregar otro turno",
  UPLOADLICENSEIMAGE: "Cargar imagen de licencia",
  IDOACCEPT: "acepto el ",
  CHANGEYOURPASSWORD: "Cambia tu contraseña",
  CHANGPASSMODALDES:
    "Shorex necesita verificar su identidad para restablecer su contraseña, se le envió el código OTP por correo electrónico/teléfono. Ingrese su correo electrónico/teléfono para restablecer la contraseña.",
  SENDCODE: "Enviar código",
  EnterOTPCODE: "Ingrese el CÓDIGO OTP",
  OTPMODALDESC:
    "Shorex necesita verificar su identidad para restablecer su contraseña. Se le envió el código OTP a través de SMS. Ingrese el código OTP a continuación y restablezca la contraseña.",
  RESENDOTP: "Reenviar OTP",
  ENTERNEWPASSWORD: "¿Ingrese nueva clave?",
  SKIP: "Saltar",
  AREYOUSRURELANG: "Would you like to change the current language?",
  AREYOURSUREACNTDEL:
    "¿Está seguro de que desea eliminar su cuenta de forma permanente?",
  SUREDELRECYCLE:
    "¿Está seguro de que desea eliminar este pedido de reciclaje?",
  PICKUPREQUEST: "Solicitudes de recogida",
  PICKUPHISTORY: "Historial de recogida",
  VEHICLELOAD: "Carga del vehículo",
  PICKUPREQUEST: "Solicitudes de recogida",
  PICKUPHISTORY: "Historial de recogida",
  VEHICLELOAD: "Carga del vehículo",
  PICKUPSREQUEST: "Solicitud de recogida",
  ROUTETOSTART: "ruta para empezar",
  ONGOINGROUTE: "ruta en marcha",
  SORTBY: "Ordenar por",
  ROUTE1: "Ruta 1",
  ROUTE2: "Ruta 2",
  SelectDate: "Seleccione fecha",

  ROUTE3: "Ruta 3",
  NOREQUESTASSIGNED: "No hay solicitud asignada en esta ruta",
  NOCOMPELTEDREQONROUT: "No hay solicitudes completadas en ruta",
  NOREQFOUND: "No se encontró ninguna solicitud",
  STARTROUTE: "Inicio Ruta ",
  ADDREQUEST: "Añadir solicitud",
  CUSTOMER: "Cliente",
  TRANSFERTHEREQ: "Transferir la solicitud",
  SEND: "Enviar",
  PASSWORDCONTAIN11: "Das Passwort enthält mindestens 11 Zeichen",
  ROUTESTART: "empezar la ruta",
  RECEIVEITEMS: "Recibir artículos",
  FALSEREQUEST: "Solicitud falsa",
  RECEIVEITEMS: "Recibir artículos",
  FALSEREQUEST: "Solicitud falsa",
  RECEIVEITEMS: "Artículos recibidos",
  RECEIVEDQUANTITY: "Cantidad recibida",
  STEEL: "acero",
  UNITS: "Unidades",
  DRIVERSCOMMENT: "Comentarios de los conductores",
  UPLOADIMG: "Cargar imagen",
  DeliveredBy: "Entregado por: (Nombre del personal del cliente)",
  WAREHOUSEMANAGER: "Administradores de almacenes",
  MANAGERNAME: "Nombre del gerente",
  PRODUCTITEMS: "artículos del producto",
  WAREHOUSEADRESSLOCATION: "Dirección y ubicación del almacén",
  WAREHOUSEHOUSELCOAITON: "Ubicación del almacén",
  DELIVERITEMS: "Entregar artículos",
  DELIVERITEMS: "Entregar artículos",
  QUANTITY: "Cantidad",
  COMPLETED: "Terminado",
  PICKUPHISTORYDETAIL: "Detalle del historial de recogida",
  PICKUPHISTORY: "Historial de recogida",
  TOTALCUSTOMER: "Cliente total",
  DRIVINGLICENSE: "identificación del conductor",
  VEHICLENUMBER: "Número de vehículo",
  JOININGDATE: "Dia de ingreso",
  YES: "Yes",
  PLEASEENTERCUSID: "Ingrese la identificación del cliente",
  Passwordsuccessfulyupdated: "La contraseña se ha cambiado correctamente",
  KG: "KG",
  Unit: "Unidad",
  Requestmarkedasfalserequest: "solicitud marcada como falsa",
  drivercomments: "Observaciones",
  requestmarkedasongoing: "solicitud en marcha",
  Confirmationalert: "confirmación!",
  COMPLETEONGOING: "Completa la ruta en curso primero",
  NOTES: "Notas",
  PLEASESELECTLOCATIONFIRST: "Seleccione la ubicación primero",
  YOURREQUEST:
    "Tu solicitud de transferencia ha sido enviada con éxito al administrador.",
  WTQTTEXT: "El valor debe ser mayor que 0",
  SELECTITEM:
    "La solicitud de reciclaje debe tener al menos un artículo con una cantidad válida  ",
  SELECT: "Seleccione",
};
