import { StyleSheet } from "react-native";
import GlobalColors from "../../../../Utils/GlobalColors";
const PickupReq_Styles = StyleSheet.create({
  Btn_Main_Route: {
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    width: 165,
    height: 33,

    borderWidth: 0.15,
    borderColor: "#707070",
    borderRadius: 2,
  },
  container: {
    flex: 1,
    backgroundColor: "#FFE713",
  },
  filterStyle: {
    marginTop: "5%",
    fontSize: 12,
    fontFamily: "Poppins_600SemiBold",
    paddingBottom: 10,
    paddingTop: "5%",
    paddingLeft: 5,
  },
  innerViewStyle: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: "6%",
    paddingBottom: "5%",
    width: "100%",
  },
  FloatingBtn: {
    backgroundColor: "#51AB1D",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    width: 165,
    height: 40,
    position: "absolute",
    bottom: "5%",
    right: "5%",
    borderWidth: 0.15,
    borderColor: "#707070",
    borderRadius: 2,
  },
  FloatingBtnOngoing: {
    backgroundColor: "#FEE612",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    width: 165,
    height: 40,
    position: "absolute",
    bottom: "5%",
    right: "5%",
    borderWidth: 0.15,
    borderColor: "#707070",
    borderRadius: 2,
  },
  innerText: {
    fontSize: 12,
    paddingLeft: "5%",
    paddingRight: "5%",
    color: GlobalColors.DarkGray,
    fontFamily: "Poppins_600SemiBold",
  },
  innerTextWhite: {
    fontSize: 12,
    paddingLeft: "5%",
    paddingRight: "5%",
    color: "white",
    fontFamily: "Poppins_600SemiBold",
  },
  filterView: {
    marginLeft: "6%",
    marginRight: "6%",
    marginTop: "2%",
  },
  buttonView1: (bgcolor) => ({
    backgroundColor: bgcolor,
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    width: 105,
    height: 32,

    borderWidth: 0.15,
    borderColor: "#707070",
    borderRadius: 2,
  }),
  buttonView2: (bgcolor2) => ({
    backgroundColor: bgcolor2,
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    width: 105,
    height: 32,
    borderWidth: 0.15,
    borderColor: "#707070",
    borderRadius: 2,
  }),

  buttonView3: (bgcolor3) => ({
    backgroundColor: bgcolor3,
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    width: 105,
    height: 32,
    borderWidth: 0.15,
    borderColor: "#707070",
    borderRadius: 2,
  }),
  innerContainer: {
    flex: 10,

    borderTopRightRadius: 50,
    borderTopLeftRadius: 50,
    backgroundColor: "white",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.9,
    shadowRadius: 8,
    elevation: 30,
  },
  header: {
    alignItems: "center",
    alignContent: "center",
    flexDirection: "row",
  },
  scrollview_style: {
    marginTop: "12%",
    marginHorizontal: "5%",

    backgroundColor: "white",
  },
  headerTitle: {
    alignSelf: "center",
    paddingLeft: "25%",
    paddingTop: "10%",
    fontFamily: "Poppins_500Medium",
    fontSize: 18,
    fontWeight: "700",
    // fontFamily:'Inter_900Black',
    paddingBottom: "2.2%",
  },
  backStyle: {
    paddingTop: "8%",
    paddingLeft: "6%",
  },
  dataContainer: {
    margin: 35,
  },
  filterStyle: {
    fontSize: 12,
    fontWeight: "bold",
    paddingBottom: 10,
    paddingLeft: 5,
    fontFamily: "Poppins_600SemiBold",
  },

  SortView: {
    flexDirection: "row",
    padding: 12,
    alignContent: "center",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderRadius: 6,
    borderColor: "#E4E9F3",
    height: 43,
    width: "100%",
  },
  ModalView: {
    marginTop: "62%",
    width: "90%",
    height: 134,
    alignContent: "center",
    alignItems: "center",
    alignSelf: "center",

    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: GlobalColors.Bordercolor,
    borderRadius: 5,
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 11,
    },
    shadowOpacity: 0.57,
    shadowRadius: 15.19,

    elevation: 10,
  },
  home_txt: {
    fontSize: 20,
    paddingLeft: "30%",
    fontWeight: "bold",
    alignSelf: "center",
  },
  loadmore: {
    flexDirection: "row",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    height: 90,
  },
});

export default PickupReq_Styles;
