import { StyleSheet } from "react-native";
import GlobalColors from "../../Utils/GlobalColors";
const Forgot_Password_Styles = StyleSheet.create({
  Main_container: {
    flex: 1,
    flexDirection: "column",
  },
  centeredview: {
    flex: 1,
    paddingTop: 80,
    alignItems: "center",

    backgroundColor: "#00000099",
  },

  text: {
    color: "#51AB1D",
    fontSize: 21,
    marginTop: "15%",
    fontFamily: "Poppins_500Medium",
  },
  absolute: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  text_style_name: {
    fontSize: 18,
    fontWeight: "bold",
    color: "black",
    marginTop: "5%",
  },
  text_style_name_change: {
    fontSize: 21,
    fontWeight: "bold",
    color: "#51AB1D",
    fontFamily: "Poppins_500Medium",
    marginTop: 10,
  },

  text_input: {
    marginTop: 5,
    borderRadius: 5,
    padding: 12,
    width: 286,
    height: 45,
    color: "gray",
    borderWidth: 1,
    borderColor: "#E4E9F3",
    fontSize: 12,
    fontFamily: "Poppins_500Medium",
  },
  heading: {
    fontSize: 9,
    fontFamily: "Poppins_400Regular",
    color: "#105398",
  },
  text_inputOTP: {
    marginTop: 5,
    borderRadius: 5,
    marginLeft: "5%",
    width: 43,
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    height: 45,
    color: "gray",
    borderWidth: 1,
    borderColor: "#E4E9F3",
    fontSize: 18,
    fontFamily: "Poppins_600SemiBold",
  },

  modalView: {
    width: "85%",
    height: "62%",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#000",
    borderRadius: 10,
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 11,
    },
    shadowOpacity: 0.57,
    shadowRadius: 15.19,

    elevation: 23,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: "#F194FF",
  },
  buttonClose: {
    backgroundColor: "#2196F3",
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
  },
  resendotp: {
    marginTop: 20,
    color: "#2172F0",
    fontSize: 14,
  },
  text_input_mobile: {
    marginTop: 5,
    borderRadius: 5,
    width: 286,
    height: 45,
    color: "gray",
    borderWidth: 1,
    borderColor: "#E4E9F3",
    fontSize: 12,
    fontFamily: "Poppins_500Medium",
  },
  Button: {
    marginTop: 20,
    height: 50,
    borderColor: "black",
    borderRadius: 4,
    backgroundColor: "#53ab1b",
    width: 286,
    alignContent: "center",
    alignItems: "center",
    padding: 10,
  },
  child_view: {
    flex: 1,
    marginTop: "10%",
    alignContent: "center",
    alignSelf: "center",
  },
  Main_container: {
    flex: 1,
    flexDirection: "column",
  },
  centeredview: {
    flex: 1,
    paddingTop: 80,
    alignItems: "center",
    backgroundColor: "#00000099",
  },

  text: {
    color: "#51AB1D",
    fontSize: 21,
    marginTop: "15%",
    fontFamily: "Poppins_500Medium",
  },
  absolute: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  inputContainer: {
    width: "80%",
    paddingVertical: "10%",
    alignSelf: "center",
  },
  text_style_name: {
    fontSize: 18,
    fontWeight: "bold",
    color: "black",
    marginTop: "5%",
  },
  text_style_name_change: {
    fontSize: 21,
    fontWeight: "bold",
    color: "#51AB1D",
    fontFamily: "Poppins_500Medium",
    marginTop: 10,
  },

  text_input: {
    marginTop: 5,
    borderRadius: 5,
    padding: 12,
    width: 286,
    height: 45,
    color: GlobalColors.grey,
    borderWidth: 1,
    borderColor: "#E4E9F3",
    fontSize: 12,
    fontFamily: "Poppins_500Medium",
  },

  txtdes: {
    fontSize: 12,
    textAlign: "center",
    padding: "5%",
    color: GlobalColors.grey,
    paddingHorizontal: 48,
  },
  TxtInput: {
    fontSize: 18,
    height: "100%",
    width: "100%",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    color: GlobalColors.grey,
  },
  modalView: {
    width: "85%",
    height: "100%",
    alignContent: "center",
    alignItems: "center",
    alignSelf: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#000",
    borderRadius: 10,
    shadowColor: "black",
    shadowOffset: {
      width: 0,
      height: 11,
    },
    shadowOpacity: 0.57,
    shadowRadius: 15.19,

    elevation: 23,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: "#F194FF",
  },
  buttonClose: {
    backgroundColor: "#2196F3",
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
  },
  resendotp: {
    marginTop: "3%",
    marginBottom: "7%",
    color: "#2172F0",
    fontSize: 14,
  },
  text_input_mobile: {
    marginTop: 5,
    borderRadius: 5,
    width: 286,
    height: 45,
    color: "gray",
    borderWidth: 1,
    borderColor: "#E4E9F3",
    fontSize: 12,
    fontFamily: "Poppins_500Medium",
  },
  Button: {
    marginTop: 20,
    height: 50,
    borderColor: "black",
    borderRadius: 4,
    backgroundColor: "#53ab1b",
    width: 286,
    alignContent: "center",
    alignItems: "center",
    padding: 10,
    marginBottom: 23,
  },
  child_view: {
    flex: 1,
    marginTop: "10%",
    alignContent: "center",
    alignSelf: "center",
  },

  prefix: {
    fontSize: 12,
    fontFamily: "Poppins_500Medium",
    top: 3,
    paddingHorizontal: 10,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  prefixView: {
    backgroundColor: "#51AB1D",
    width: "20%",
    alignItems: "center",
    height: 45,
    marginTop: 10,
    padding: 10,
    borderRadius: 3,
    marginRight: 10,
  },
});
export default Forgot_Password_Styles;
