import { StyleSheet } from "react-native";

const Home_Screen_Styles = StyleSheet.create({
  cardview: {
    flex: 6,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 2,
    elevation: 20,
  },
  calenderView: {
    flexDirection: "row",
    padding: 15,
    borderWidth: 1,
    borderRadius: 6,
    borderColor: "#51AB1D",
    justifyContent: "space-between",
    paddingHorizontal: "8%",
  },
  container: {
    flex: 1,
    backgroundColor: "#FFE713",
  },
  imgview: {
    marginTop: 60,
    width: "100%",
  },
  home_banner: {
    width: 306,
    height: 164,
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 20,
  },
  GridListView: {
    flexDirection: "row",
    marginTop: 20,
    alignItems: "flex-end",
    alignContent: "flex-end",
    alignSelf: "flex-end",
  },
  childcontainer: {
    flex: 10,
    borderTopRightRadius: 50,
    borderTopLeftRadius: 50,
    backgroundColor: "white",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.9,
    shadowRadius: 8,
    elevation: 10,
    alignContent: "center",
    alignItems: "flex-end",
  },
  home_txt: {
    paddingTop: "8%",
    fontFamily: "Poppins_500Medium",
    fontSize: 18,
    fontWeight: "700",
    // fontFamily:'Inter_900Black',
    fontSize: 18,
    alignSelf: "center",
    fontFamily: "Poppins_500Medium",
  },
  buttons_row: {
    marginTop: 20,
    flexDirection: "row",
    alignContent: "center",
    alignItems: "center",
  },
  cardviews: {
    height: 120,
    width: 110,
    borderWidth: 0.5,
    backgroundColor: "#f5eeed",
    borderColor: "#999393",
    borderRadius: 10,
    margin: 10,
    backgroundColor: "white",
    alignContent: "center",
    alignItems: "center",
  },
  gridStyle: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    height: 120,
    borderWidth: 1,
    borderColor: "#E4E9F3",
    borderRadius: 4,
    margin: 10,
  },
  listStyle: {
    flex: 1,
    flexDirection: "row",
    height: 60,
    borderWidth: 0.5,
    paddingLeft: 50,
    alignContent: "center",
    alignItems: "center",
    borderColor: "#E4E9F3",
    borderRadius: 10,
    margin: 10,
  },

  gridText: {
    paddingTop: 30,
    fontSize: 10,
    color: "black",
    fontFamily: "Poppins_600SemiBold",
  },
  listText: {
    fontSize: 10,
    color: "black",
    fontFamily: "Poppins_600SemiBold",
    paddingLeft: 25,
    color: "black",
  },
  btnNormal: {
    borderColor: "blue",
    borderWidth: 1,
    borderRadius: 10,
  },
  btnPress: {
    borderColor: "blue",
    borderWidth: 1,
  },
});
export default Home_Screen_Styles;
